import "./globals.css";
import { Itim } from 'next/font/google'

const itim = Itim({
  subsets: ['latin'],
  weight:['400']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${itim.className}`}
      >
        {children}
      </body>
    </html>
  );
}
